version: '3.8'

services:
  course-service:
    build:
      context: ./learnify-course-service
    container_name: learnify-course-service
    ports:
      - "8088:8088"
    env_file: .env
    depends_on:
      - learnify_db
    networks:
      - learnify

  motivation-service:
    build:
      context: ./LearnifyMotivationService
    container_name: learnify-motivation-service
    ports:
      - "8082:8082"
    env_file: .env
    networks:
      - learnify

  learnify_db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - learnify
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  learnify:
